batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
eval_split: split/eval/car.txt
checkpoint_path: 'models/car/checkpoints/model_epoch_0060.pth'
experiment_name: car
hidden_num: 128
latent_dim: 128
logging_root: ./eval
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 3000
on_surface_points: 4000
point_cloud_path: datasets/car/surface_pts_n_normal
steps_til_summary: 100
