batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
eval_split: split/eval/gripper.txt
checkpoint_path: /logs/gripper/checkpoints/model_final.pth'
experiment_name: gripper
hidden_num: 128
shape_latent_dim: 128
config_latent_dim: 128
logging_root: ./eval
lr: 0.0001
max_points: 100000
model_type: sine
num_instances: 2000
num_categories: 2
on_surface_points: 4000
point_cloud_path: /datasets/Gripper/surface_pts_n_normal
steps_til_summary: 100