batch_size: 64
epochs: 40
epochs_til_checkpoint: 5
expand: 0.01
experiment_name: gripper
hidden_num: 128
shape_latent_dim: 128
config_latent_dim: 128
logging_root: ./logs
loss_correct: 50.0
loss_grad_deform: 5
loss_grad_temp: 100.0
lr: 0.0001
max_points: 100000
model_type: sine
num_instances: 2000
num_categories: 2
on_surface_points: 4000
point_cloud_path: /datasets/Gripper/surface_pts_n_normal
steps_til_summary: 100
train_split: split/train/gripper.txt
